Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Private network with a specific IP
  config.vm.network "private_network", ip: "192.168.56.82"

  # Forward ports for Jenkins and Kubernetes service
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 30001, host: 30001, host_ip: "127.0.0.1"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  # Provision Docker
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sudo apt-get update
    sudo apt-get install -y \
        ca-certificates \
        curl \
        gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin
  SHELL
end
